# 사이트 기본 정보

# 사용할 테마
theme: jekyll-theme-chirpy

# 사이트 언어 및 타임존
lang: ko
timezone: Asia/Seoul

# 사이트 메타 정보 (SEO 및 피드용)
title: ProDevJune Blog
description: AI + Programming Lab
tagline: Development + AI Toolkit

# 배포 주소 설정
url: "https://ProDevJune.github.io"
baseurl: "/ProDevJune"

# 소셜 정보 (footer와 SEO에 사용)
github:
  username: ProDevJune
social:
  name: Jayden
  email: gd2u37@gmail.com
  links:
    - https://github.com/ProDevJune

# 색상 모드 (시스템 기본 또는 강제 설정 가능)
theme_mode: # [light | dark], 기본은 시스템 설정 따름

# 수식/다이어그램 지원
math: true
mermaid: true

# 글 개요(TOC) 기본 활성화
toc: true

# PWA 기능 사용 (설치 및 오프라인 지원)
pwa:
  enabled: true
  cache:
    enabled: true

# 페이지네이션
paginate: 10

# 태그/카테고리 아카이브 활성화
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/